### ISSUE TITLE
question about cuda out of memory

### ISSUE THREAD

**Issue by jinxxo-j** [minwoo0611/HeLiOS#8]
Hi there! I have one more question about HeLiOS, so I’m opening this issue.

According to the paper, you trained the model on an RTX 3090 GPU (24 GB). However, when I run the training with the default settings, I encounter a cuda_out_of_memory error. Could this mean that some of the training parameters in config_baseline_helios.txt are misconfigured?

The error log is shown below:

root@mutalisk8:/mydata/home/jinwoo/HeLiOS# python3 training/train.py --config config/config_baseline_helios.txt --model_config config/model_helios.txt
/opt/conda/lib/python3.10/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Training config path: config/config_baseline_helios.txt
Model config path: config/model_helios.txt
Debug mode: False
Parameters:
params_path: config/config_baseline_helios.txt
model_params_path: config/model_helios.txt
debug: False
dataset_folder: /mydata/mnt/hdd1/jinwoo/data/helipr
model_name: HeLiOS_default_trainning
save_freq: 10
num_workers: 4
batch_size: 2048
batch_split_size: 64
batch_expansion_th: None
batch_size_limit: 2048
batch_expansion_rate: None
val_batch_size: 256
lr: 0.001
epochs: 80
optimizer: Adam
scheduler: MultiStepLR
scheduler_milestones: [40, 70]
weight_decay: 0.0001
similarity: euclidean
aug_mode: 1
set_aug_mode: 1
train_file: training.pickle
val_file: validation.pickle
test_file: None
eval_db_file: Roundabout_evaluation_db.pickle
eval_query_file: Roundabout_evaluation_query.pickle
positives_per_query: 4
tau1: 0.01
margin: None
p_sp_distance: 0.02
sp_n_distance: 0.19
truncated_weight: 0.8
guided_p_sp_weight: 0.1
guided_sp_n_weight: 0.1
Model parameters:
model_params_path: config/model_helios.txt
model: HeLiOS
output_dim: 256
coordinates: cartesian
quantization_step: 0.01 [m]
quantizer: <datasets.quantization.CartesianQuantizer object at 0x7f642cf5f700>
normalize_embeddings: False
feature_size: 256
planes: (64, 128, 64, 32)
layers: (1, 1, 1, 1)
num_top_down: 2
conv0_kernel_size: 5
radial_window_size: [ 1.8  1.8 10. ]
voxel_window_size: [4. 4. 4.]
expansion_rate: 1.5
num_clusters: 64
cluster_dim: 128
use_token: True

Model name: HeLiOS_default_trainning
Model class: HeLiOS
Total parameters: 4260018
# output channels : 256
Model device: NVIDIA TITAN RTX
41079 queries in the dataset
6776 queries in the dataset
Training:   0%|                                                                  | 0/80 [00:00<?, ?it/s]tensor(0.8184, device='cuda:0', dtype=torch.float64, grad_fn=<AddBackward0>)
Training:   0%|                                                                  | 0/80 [01:46<?, ?it/s]
Traceback (most recent call last):
  File "/mydata/home/jinwoo/HeLiOS/training/train.py", line 34, in <module>
    do_train(params)
  File "/mydata/home/jinwoo/HeLiOS/training/trainer.py", line 289, in do_train
    batch_stats = multistaged_training_step(
  File "/mydata/home/jinwoo/HeLiOS/training/trainer.py", line 211, in multistaged_training_step
    update_model(model, batch, embeddings_grad, optimizer, device)
  File "/mydata/home/jinwoo/HeLiOS/training/trainer.py", line 166, in update_model
    embeddings.backward(
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.76 GiB (GPU 0; 23.46 GiB total capacity; 13.86 GiB already allocated; 3.57 GiB free; 18.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by minwoo0611** [comment]
Sorry for late replying, @jinxxo-j 

We used 4 RTX 3090 GPU, but if you use the single one, we recommend you to reduce the batch_split_size: 64 to 16.

**Comment by jinxxo-j** [comment]
Thank you for your response. I resolved the issue by reducing the batch size.
